//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicFestival
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выступления
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Выступления()
        {
            this.Сцены = new HashSet<Сцены>();
            this.ВыступленияИсполнителя = new HashSet<ВыступленияИсполнителя>();
            this.ВыступленияНаСцене = new HashSet<ВыступленияНаСцене>();
        }
    
        public int id_выступления { get; set; }
        public Nullable<int> id_исполнителя { get; set; }
        public Nullable<System.TimeSpan> время_начала { get; set; }
        public Nullable<System.TimeSpan> время_окончания { get; set; }
    
        public virtual Исполнители Исполнители { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сцены> Сцены { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ВыступленияИсполнителя> ВыступленияИсполнителя { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ВыступленияНаСцене> ВыступленияНаСцене { get; set; }
    }
}
