//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicFestival
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказБилета
    {
        public int id { get; set; }
        public int id_билета { get; set; }
        public int id_посетителя { get; set; }
        public int id_заказа { get; set; }
    
        public virtual Билеты Билеты { get; set; }
        public virtual Заказы Заказы { get; set; }
        public virtual Посетители Посетители { get; set; }
    }
}
