//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicFestival
{
    using System;
    using System.Collections.Generic;
    
    public partial class Песни
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Песни()
        {
            this.ВыступленияИсполнителя = new HashSet<ВыступленияИсполнителя>();
        }
    
        public int id_песни { get; set; }
        public Nullable<int> id_исполнителя { get; set; }
        public string название_песни { get; set; }
        public string продолжительность_песни { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ВыступленияИсполнителя> ВыступленияИсполнителя { get; set; }
        public virtual Исполнители Исполнители { get; set; }
    }
}
