//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicFestival
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сцены
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сцены()
        {
            this.ТаблицаСвязи3 = new HashSet<ТаблицаСвязи3>();
        }
    
        public int id_сцены { get; set; }
        public Nullable<int> id_выступления { get; set; }
        public Nullable<int> вместимость_сцены { get; set; }
    
        public virtual Выступления Выступления { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТаблицаСвязи3> ТаблицаСвязи3 { get; set; }
    }
}
