//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicFestival
{
    using System;
    using System.Collections.Generic;
    
    public partial class УчетИспонителей
    {
        public string Исполнитель { get; set; }
        public string Музыкальный_Жанр { get; set; }
        public Nullable<System.TimeSpan> Время_Начала { get; set; }
        public Nullable<System.TimeSpan> Время_Окончания { get; set; }
        public int Сцена { get; set; }
    }
}
